const coursesData = {
    IT: [
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Web Development', enrolled: 120, name: 'React for Beginners' },
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Web Development', enrolled: 95, name: 'JavaScript Essentials' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Data Science', enrolled: 150, name: 'Data Analysis with Python' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Cybersecurity', enrolled: 80, name: 'Introduction to Cybersecurity' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Cloud Computing', enrolled: 60, name: 'AWS Fundamentals' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Mobile Development', enrolled: 110, name: 'iOS App Development' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Game Development', enrolled: 70, name: 'Unity Game Development' },
    ],
    Health: [
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Nutrition', enrolled: 200, name: 'Healthy Eating Habits' },
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Fitness', enrolled: 150, name: 'Yoga for Beginners' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Mental Health', enrolled: 180, name: 'Mindfulness Meditation' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'First Aid', enrolled: 90, name: 'Basic First Aid Training' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Health Coaching', enrolled: 75, name: 'Health Coaching Certification' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Public Health', enrolled: 60, name: 'Introduction to Public Health' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Mental Health', enrolled: 130, name: 'Coping with Stress' },
    ],
    Business: [
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Entrepreneurship', enrolled: 140, name: 'Starting Your Own Business' },
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Marketing', enrolled: 110, name: 'Digital Marketing Strategies' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Finance', enrolled: 95, name: 'Personal Finance 101' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Management', enrolled: 85, name: 'Effective Leadership Skills' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Sales', enrolled: 120, name: 'Sales Techniques for Success' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Business Strategy', enrolled: 70, name: 'Strategic Planning' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Project Management', enrolled: 100, name: 'Project Management Basics' },
    ],
    Language: [
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Spanish', enrolled: 130, name: 'Spanish for Beginners' },
      { id: 2, image: 'https://via.placeholder.com/300x150', category: 'French', enrolled: 110, name: 'Conversational French' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'German', enrolled: 90, name: 'German Language Basics' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Mandarin', enrolled: 80, name: 'Introduction to Mandarin' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Italian', enrolled: 70, name: 'Italian for Travelers' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Japanese', enrolled: 60, name: 'Japanese Language Essentials' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'English', enrolled: 150, name: 'Advanced English Grammar' },
    ],
    Management: [
      { id: "66de969a3e51f04a4b56b0a1", image: 'https://via.placeholder.com/300x150', category: 'Project Management', enrolled: 120, name: 'Agile Project Management' },
      { id: 2, image: 'https://via.placeholder.com/300x150', category: 'Team Management', enrolled: 100, name: 'Building Effective Teams' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Time Management', enrolled: 90, name: 'Time Management Techniques' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Conflict Resolution', enrolled: 80, name: 'Conflict Resolution Skills' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Change Management', enrolled: 70, name: 'Managing Change in Organizations' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Performance Management', enrolled: 60, name: 'Performance Management Strategies' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Leadership', enrolled: 150, name: 'Leadership Development Program' },
    ],
    'Personal development': [
      { id: 1, image: 'https://via.placeholder.com/300x150', category: 'Self-Improvement', enrolled: 140, name: 'Personal Growth Strategies' },
      { id: 2, image: 'https://via.placeholder.com/300x150', category: 'Mindfulness', enrolled: 120, name: 'Mindfulness for Everyday Life' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Goal Setting', enrolled: 100, name: 'Effective Goal Setting' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Motivation', enrolled: 90, name: 'Staying Motivated' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Communication', enrolled: 80, name: 'Effective Communication Skills' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Confidence', enrolled: 70, name: 'Building Self-Confidence' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Stress Management', enrolled: 60, name: 'Stress Management Techniques' },
    ],
    Engineering: [
      { id: 1, image: 'https://via.placeholder.com/300x150', category: 'Mechanical Engineering', enrolled: 130, name: 'Introduction to Mechanical Engineering' },
      { id: 2, image: 'https://via.placeholder.com/300x150', category: 'Electrical Engineering', enrolled: 110, name: 'Basics of Electrical Engineering' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Civil Engineering', enrolled: 90, name: 'Fundamentals of Civil Engineering' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Software Engineering', enrolled: 80, name: 'Software Development Lifecycle' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Chemical Engineering', enrolled: 70, name: 'Introduction to Chemical Engineering' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Environmental Engineering', enrolled: 60, name: 'Sustainable Engineering Practices' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Aerospace Engineering', enrolled: 150, name: 'Basics of Aerospace Engineering' },
    ],
    'Sales and Marketing': [
      { id: 1, image: 'https://via.placeholder.com/300x150', category: 'Sales', enrolled: 140, name: 'Sales Strategies for Success' },
      { id: 2, image: 'https://via.placeholder.com/300x150', category: 'Marketing', enrolled: 120, name: 'Content Marketing Essentials' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Digital Marketing', enrolled: 100, name: 'SEO Basics' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Social Media', enrolled: 90, name: 'Social Media Marketing' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Branding', enrolled: 80, name: 'Building a Brand' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Email Marketing', enrolled: 70, name: 'Email Marketing Strategies' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Market Research', enrolled: 60, name: 'Conducting Market Research' },
    ],
    'Art and Design': [
      { id: 1, image: 'https://via.placeholder.com/300x150', category: 'Graphic Design', enrolled: 130, name: 'Graphic Design Basics' },
      { id: 2, image: 'https://via.placeholder.com/300x150', category: 'Photography', enrolled: 110, name: 'Photography for Beginners' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Painting', enrolled: 90, name: 'Watercolor Painting Techniques' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Fashion Design', enrolled: 80, name: 'Introduction to Fashion Design' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Interior Design', enrolled: 70, name: 'Interior Design Fundamentals' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Digital Art', enrolled: 60, name: 'Creating Digital Art' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Music', enrolled: 150, name: 'Music Production Basics' },
    ],
    Finance: [
      { id: 1, image: 'https://via.placeholder.com/300x150', category: 'Investing', enrolled: 140, name: 'Investing 101' },
      { id: 2, image: 'https://via.placeholder.com/300x150', category: 'Personal Finance', enrolled: 120, name: 'Budgeting Basics' },
      { id: 3, image: 'https://via.placeholder.com/300x150', category: 'Accounting', enrolled: 100, name: 'Introduction to Accounting' },
      { id: 4, image: 'https://via.placeholder.com/300x150', category: 'Financial Planning', enrolled: 90, name: 'Financial Planning Strategies' },
      { id: 5, image: 'https://via.placeholder.com/300x150', category: 'Taxation', enrolled: 80, name: 'Understanding Taxes' },
      { id: 6, image: 'https://via.placeholder.com/300x150', category: 'Corporate Finance', enrolled: 70, name: 'Corporate Finance Basics' },
      { id: 7, image: 'https://via.placeholder.com/300x150', category: 'Real Estate', enrolled: 60, name: 'Real Estate Investing' },
    ],
  };
  export default coursesData;
  